2024-02-26 14:28:34.160 [info] 실험 'pythonaa'이(가) 활성 상태입니다.
2024-02-26 14:28:34.160 [info] 실험 'pythonRecommendTensorboardExt'이(가) 활성 상태입니다.
2024-02-26 14:28:34.160 [info] 실험 'pythonREPLSmartSend'이(가) 활성 상태입니다.
2024-02-26 14:28:34.161 [info] 실험 'pythonTerminalEnvVarActivation'이(가) 활성 상태입니다.
2024-02-26 14:28:34.161 [info] 실험 'pythonTestAdapter'이(가) 활성 상태입니다.
2024-02-26 14:28:34.161 [info] Default formatter is set to null for workspace /root
2024-02-26 14:28:34.161 [info] Test server listening.
2024-02-26 14:28:34.186 [info] > C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -I ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-02-26 14:28:34.188 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-02-26 14:28:34.191 [error] [Error: Command failed: C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
/bin/sh: 1: C:UsersAdministratorAppDataLocalProgramsPythonPython310python.exe: not found

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:526:35)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:514:28)
	at Pipe.<anonymous> (node:net:323:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py'
}
2024-02-26 14:28:36.206 [info] > C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -I ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
2024-02-26 14:28:36.208 [error] [Error: Command failed: C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py
/bin/sh: 1: C:UsersAdministratorAppDataLocalProgramsPythonPython310python.exe: not found

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:526:35)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:514:28)
	at Pipe.<anonymous> (node:net:323:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -I /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.0.1/pythonFiles/interpreterInfo.py'
}
2024-02-26 14:28:36.228 [info] > C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -c "import sys;print(sys.executable)"
2024-02-26 14:28:36.231 [error] [Error: Command failed: C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe -c "import sys;print(sys.executable)"
/bin/sh: 1: C:UsersAdministratorAppDataLocalProgramsPythonPython310python.exe: not found

	at ChildProcess.exithandler (node:child_process:420:12)
	at ChildProcess.emit (node:events:526:35)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:514:28)
	at Pipe.<anonymous> (node:net:323:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -c "import sys;print(sys.executable)"'
}
2024-02-26 14:28:37.717 [info] Pylance 언어 서버를 시작하는 중입니다.
